# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import dynamic_ks_pb2 as dynamic__ks__pb2


class DynamicKSStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.setKey = channel.unary_unary(
        '/DynamicKS/setKey',
        request_serializer=dynamic__ks__pb2.request.SerializeToString,
        response_deserializer=dynamic__ks__pb2.response.FromString,
        )
    self.getKey = channel.unary_unary(
        '/DynamicKS/getKey',
        request_serializer=dynamic__ks__pb2.key.SerializeToString,
        response_deserializer=dynamic__ks__pb2.value.FromString,
        )


class DynamicKSServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def setKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getKey(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DynamicKSServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'setKey': grpc.unary_unary_rpc_method_handler(
          servicer.setKey,
          request_deserializer=dynamic__ks__pb2.request.FromString,
          response_serializer=dynamic__ks__pb2.response.SerializeToString,
      ),
      'getKey': grpc.unary_unary_rpc_method_handler(
          servicer.getKey,
          request_deserializer=dynamic__ks__pb2.key.FromString,
          response_serializer=dynamic__ks__pb2.value.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DynamicKS', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
